- hosts: dbwr3.localdomain
  tasks:
  - name: Log out from emcli session if session already exists
    become: false
    become_user: root
    shell: /em/middleware/bin/emcli logout
    ignore_errors: true
    register: logout_results
  - debug:
      var: logout_results.stdout_lines
      
  - name: Login to Enterprise manager
    shell: /em/middleware/bin/emcli login -username=sysman -password=welcome1
    register: login_results
  - debug:
      var: login_results.stdout_lines
      
  - name: Get Gold Images
    shell: /em/middleware/bin/emcli db_software_maintenance -getImages -columnName=image_id,image_name
    register: gold_results
  - debug:
      var: gold_results.stdout_lines
      
      
      
     
