- hosts: dbwr3.localdomain
  tasks:
  - name: Patching - Deploy Image
    become: false
    become_user: root
    shell: |
      cd /em/middleware/bin/
      pwd
    register: logout_results
  - debug:
      var: login_results.stdout_lines
     
