- hosts: dbwr3.localdomain
  tasks:
  - name: Execute fleet patching - deploy image 
    become: false
    become_user: root
    shell: /home/oracle/display.sh
    register: fleet_dp_results

  - debug:
      var: fleet_dp_results.stdout_lines


