- hosts: dbwr3.localdomain
  tasks:
  - name: Login to EM
    become: false
    become_user: root
    shell: /em/middleware/bin/emcli login -username=sysman -password=welcome1
    shell: /em/middleware/bin/emcli db_software_maintenance -getImages
    register: fleet_dp_results
  - debug:
      var: fleet_dp_results.stdout_lines
      
