- hosts: dbwr3.localdomain
  tasks:
  - name: Changing Directory
    become: false
    become_user: root
    shell: cd /em/middleware/bin/
  
  - name: Login to Enterprise manager
    shell: pwd >> resp.txt | cat resp.txt
    register: login_results
  - debug:
      var: login_results.stdout_lines
      
      
      
     
