- hosts: dbwr3.localdomain
  tasks:
  - name: Execute shell to checkout password from PAM and sync named credentials
    become: false
    become_user: root
    shell: ./get_pampass.sh
    register: sync_pre_results

  - debug:
      var: sync_pre_results.stdout_lines

- hosts: localhost
  tasks:
  - name: Execute Database Provisioning or Snap Clone using emcli commands
    become: false
    become_user: root
    shell: sleep 1m

  - debug:
      msg: "\n\nEnterprise Manager process compelted now password can be checkedin back to PAM\n\n"

- hosts: localhost
  tasks:
  - name: Execute shell to checkin password to PAM
    become: false
    become_user: root
    shell: ./put_pampass.sh
    register: sync_post_results

  - debug:
      var: sync_post_results.stdout_lines


