- hosts: dbwr3.localdomain
  tasks:
  - name: Changing Directory
    become: false
    become_user: root
    shell: cd /em/middleware/bin/
    register: login_results11
    shell: pwd >> resp.txt | cat resp.txt
    register: login_results12
  - debug:
      var: login_results11.stdout_lines
  - debug:
      var: login_results12.stdout_lines
  - name: Login to Enterprise manager
    shell: pwd >> resp.txt | cat resp.txt
    register: login_results2
  - debug:
      var: login_results2.stdout_lines
      
      
      
     
