- hosts: dbwr3.localdomain
  tasks:
  - name: Execute fleet patching - deploy image 
    become: false
    become_user: root
    shell: /em/middleware/bin/emcli login -username=sysman -password=welcome1
    register: fleet_dp_results

  - debug:
      var: fleet_dp_results.stdout_lines


