- hosts: dbwr3.localdomain
  tasks:
  - name: Changing Directory
    become: false
    become_user: root
    shell: pwd >> resp.txt | cat resp.txt
    register: login_results1
  - debug:
      var: login_results1.stdout_lines
      
  - name: Login to Enterprise manager
    shell: pwd >> resp.txt | cat resp.txt
    register: login_results2
  - debug:
      var: login_results2.stdout_lines
      
      
      
     
