- hosts: dbwr3.localdomain
  tasks:
  - name: Log out from emcli session if session already exists
    become: false
    become_user: root
    command: /em/middleware/bin/emcli logout
    register: logout_results
  - debug:
      var: logout_results.stdout_lines
      
  - name: Login to Enterprise manager
    command: /em/middleware/bin/emcli login -username=sysman -password=welcome1
    register: login_results
  - debug:
      var: login_results.stdout_lines
      
      
      
     
